### ISSUE TITLE
Request: edit incorrect step in README.txt

### ISSUE THREAD

**Issue by colematt** [UCSD-PL/ivt#1]
Step 3) Build the repo in a directory $(REPO_BUILD_DIR) has the following line:

`./configure --enable-optimized=1 --with-binutils-include=$(BINUTILS_SRC)/include`

which should actually read

`../$(REPO_DIR)/configure --enable-optimized=1 --with-binutils-include=$(BINUTILS_SRC)/include`

since the previous step makes the working directory equal to `$(REPO_BUILD_DIR)`, and it does not have a `configure` script.

**Comment by d1m0** [comment]
Thanks for catching that! Fixed
